import os

from dotenv import load_dotenv

load_dotenv()


AZURE_OPENAI_ENDPOINT = os.getenv("AZURE_OPENAI_ENDPOINT")
AZURE_OPENAI_API_KEY = os.getenv("AZURE_OPENAI_API_KEY")
AZURE_RERANK_ENDPOINT = os.getenv("AZURE_RERANK_ENDPOINT")
AZURE_RERANK_API_KEY = os.getenv("AZURE_RERANK_API_KEY")
AZURE_RERANK_DEPLOYMENT = os.getenv("AZURE_RERANK_DEPLOYMENT")
AZURE_CHAT_DEPLOYMENT = os.getenv("AZURE_CHAT_DEPLOYMENT")
AZURE_EMBEDDING_DEPLOYMENT = os.getenv("AZURE_EMBEDDING_DEPLOYMENT")
AZURE_OPENAI_API_VERSION=os.getenv("AZURE_OPENAI_API_VERSION")
AZURE_SEARCH_ENDPOINT = os.getenv("AZURE_SEARCH_ENDPOINT")
AZURE_SEARCH_API_KEY = os.getenv("AZURE_SEARCH_API_KEY")
AZURE_SEARCH_INDEX = os.getenv(
    "AZURE_SEARCH_INDEX",
    "rag-1789033469043"
)

MAX_CONTEXT_TOKENS = int(
    os.getenv("MAX_CONTEXT_TOKENS", "5000")
)

TOP_K = int(
    os.getenv("TOP_K", "10")
)